### ISSUE TITLE
Value of type error in TapURLSerializer.swift

### ISSUE THREAD

**Issue by bhanu501** [Tap-Payments/goSellSDK-iOS#1]
getting following error in **TapURLSerializer.swift** file
in **line number 58**
under **case .array(let params):**
Value of type '[CustomStringConvertible]' has no member 'compactMap'

**Comment by tapmobiledeveloper** [comment]
`compactMap` method is available starting from Swift 4.1 only.

**Comment by bhanu501** [comment]
ok. thank you
