### ISSUE TITLE
There is nothing in goSellSDK and can't get payButton 

### ISSUE THREAD

**Issue by Ruman1234** [Tap-Payments/goSellSDK-iOS#10]
<img width="905" alt="Screenshot 2019-04-10 at 4 22 04 PM" src="https://user-images.githubusercontent.com/37799754/55874911-2df4d280-5bad-11e9-8aea-8a02b0a29256.png">
<img width="902" alt="Screenshot 2019-04-10 at 4 22 26 PM" src="https://user-images.githubusercontent.com/37799754/55874912-2df4d280-5bad-11e9-97eb-600ef4afb0f0.png">
<img width="837" alt="Screenshot 2019-04-10 at 4 23 01 PM" src="https://user-images.githubusercontent.com/37799754/55874914-2df4d280-5bad-11e9-9a58-ce5248612301.png">
<img width="857" alt="Screenshot 2019-04-10 at 4 23 11 PM" src="https://user-images.githubusercontent.com/37799754/55874916-2e8d6900-5bad-11e9-8738-cb53e8f9a2ed.png">

**Comment by Ruman1234** [comment]
why this is happening

**Comment by tapmobiledeveloper** [comment]
@Ruman1234 update the SDK to version 2.x using `pod update`, then open the workspace and build. Only after the build start the integration
