### ISSUE TITLE
Serialization issue

### ISSUE THREAD

**Issue by mats-claassen** [Tap-Payments/goSellSDK-iOS#11]
Hi, I am getting an error in the Tap SDK since yesterday saying `Serialization error has ocurred` whenever the user enters a credit card in the SDK. It is basically impossible to perform purchase or authorize calls.

**Comment by ali-tap** [comment]
@mats-claassen pls add a full bug report, as this isn't clear enough. Logs, steps to recreate the bug so we can try to resolve it.

**Comment by mats-claassen** [comment]
Sorry. It was an issue happening in Sandbox but not in production, it seems. Also KNET payments seem to work.
When the user is directed to the Tap SDK page and chooses to pay with a MasterCard or Visa test card, an alert will pop up with the mentioned error (`Serialization error has ocurred`)

I am using version 2.2.2 but it also happens with version 2.2.4.

However, testing today it is working again so I will close this issue

**Comment by krunal19** [comment]
![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-07-29 at 20 16 49](https://user-images.githubusercontent.com/51108315/88815401-f31b1180-d1d8-11ea-90d7-fd12d7581d6e.png)
I'm not able to pay
