### ISSUE TITLE
Xcode 11: not compiling

### ISSUE THREAD

**Issue by mats-claassen** [Tap-Payments/goSellSDK-iOS#13]
Hi,

The SDK (v 2.2.4) is not compiling for my project in Xcode 11. It was working in the previous versions of Xcode.

Thanks

**Comment by SarathPUnni** [comment]
We fixed it on [this branch](https://github.com/SarathPUnni/goSellSDK-iOS/tree/fix-xcode-11)

**Comment by kholdunn** [comment]
@mats-claassen we are updating our kits to be compatible with Xcode 11 / iOS 13
you can test our beta versions for SDK and TapAdditionsKit
`'goSellSDK', '2.2.7-beta' 
'TapAdditionsKit', '1.3.5-beta'`

**Comment by ali-tap** [comment]
Resolved.

[Release 2.2.7](https://github.com/Tap-Payments/goSellSDK-iOS/releases/tag/2.2.7)
