### ISSUE TITLE
Xcode 11 : ios 13 not compiling 

### ISSUE THREAD

**Issue by nickbhavsar** [Tap-Payments/goSellSDK-iOS#15]
Got an Error while building an app in xcode 11 , got an error while tap view got disappear after respectfull action like (saved card, cancel card etc. ), when tap's custom view got disappear its crashing

**Comment by ali-tap** [comment]
@nickbhavsar yes, we are working on the bug. Thanks for reporting it. Will notify you and close this once it's resolved.

**Comment by kholdunn** [comment]
@nickbhavsar we are updating our kits to be compatible with Xcode 11 / iOS 13
you can test our beta versions for SDK and TapAdditionsKit
`'goSellSDK', '2.2.7-beta' 
'TapAdditionsKit', '1.3.5-beta'`

**Comment by ali-tap** [comment]
Resolved in release 2.2.7

**Comment by nickbhavsar** [comment]
same issue i'm facing in 2.2.10 version again, pls update me

**Comment by nickbhavsar** [comment]
in ios 13.3
