### ISSUE TITLE
SDK is not working in iOS 13

### ISSUE THREAD

**Issue by mob-rockstar** [Tap-Payments/goSellSDK-iOS#19]
I have placed PayButton in storyboard and set datasource and delegate.
But it is only showing paybutton without any text(green background) and not working even if I tap the paybutton. Nothing happened. 

       // Transaction mode
        GoSellSDK.mode = .sandbox        

        // Set language
        if(UserInfo.sharedInstance.currentLanguage == KEY_ENGLISH)
        {
            GoSellSDK.language = "en"
        }
        else {
            GoSellSDK.language = "ar"
        }
        
        // Session Delegate
        self.payButton.delegate = self
        
        // Session Datasource
        self.payButton.dataSource = self
        
        // Session Appearance
        self.payButton.appearance = self

**Comment by kholdunn** [comment]
for integration clarification please contact the support team at tap.company

**Comment by nunepradeepkumar** [comment]
> I have placed PayButton in storyboard and set datasource and delegate.
> But it is only showing paybutton without any text(green background) and not working even if I tap the paybutton. Nothing happened.
> 
> ```
>    // Transaction mode
>     GoSellSDK.mode = .sandbox        
> 
>     // Set language
>     if(UserInfo.sharedInstance.currentLanguage == KEY_ENGLISH)
>     {
>         GoSellSDK.language = "en"
>     }
>     else {
>         GoSellSDK.language = "ar"
>     }
>     
>     // Session Delegate
>     self.payButton.delegate = self
>     
>     // Session Datasource
>     self.payButton.dataSource = self
>     
>     // Session Appearance
>     self.payButton.appearance = self
> ```

Hi,
 I am also facing same issue Can you help me on this.
