### ISSUE TITLE
Errors with the latest Xcode version 12.0

### ISSUE THREAD

**Issue by AMSH92** [Tap-Payments/goSellSDK-iOS#31]
Hey team,
I upgraded to the latest Xcode version and when I try to build my project I found many issues in your SDK.
`Struct 'CGFloat' does not exist in module 'CoreGraphics'`
`Struct 'Data' does not exist in module 'Foundation'`
`Struct 'URLRequest' does not exist in module 'Foundation'`
`Class 'JSONDecoder' does not exist in module 'Foundation'`
`Struct 'Locale' does not exist in module 'Foundation'`
`Struct 'CharacterSet' does not exist in module 'Foundation'`

FYI @AbdullahAlajmi

**Comment by Parth-Patoliya** [comment]
Same issue

**Comment by AMSH92** [comment]
I downgraded to Xcode 11.7 and everything is working just fine. Please resolve this issue :)

**Comment by nunepradeepkumar** [comment]
same issue.

**Comment by sadanandlowanshi** [comment]
any solution

**Comment by nicolantean** [comment]
Same issue

**Comment by AMSH92** [comment]
SDK has been updated
