### ISSUE TITLE
Always getting error in the token method.

### ISSUE THREAD

**Issue by syam82** [Tap-Payments/goSellSDK-iOS#4]
Always getting the below error for Token

Underlying error: The data couldn’t be read because it is missing.
URL response: <NSHTTPURLResponse: 0x141ae2a20> { URL: https://api.tap.company/v1.1/token/ } { Status Code: 403, Headers {
    Connection =     (
        "keep-alive"
    );
    "Content-Length" =     (
        75
    );
    "Content-Type" =     (
        "application/json; charset=utf-8"
    );
    Date =     (
        "Thu, 07 Feb 2019 06:59:07 GMT"
    );
    Etag =     (
        "W/\"4b-lAo6cX0/0Ucuxwlw7scmQzWPSJA\""
    );
    "X-Powered-By" =     (
        Express
    );
} }

**Comment by tapmobiledeveloper** [comment]
@syam82 HTTP status code 403 says that you don't have permission to call that API. Please note that calling token API directly requires PCI compliance. Please contact our support in case if you have it.

In addition to that, SDK version `1.x` is not maintained any more. Please use version `2.x` instead which has all payment process covered (with UI) and does not require PCI. In addition to that, if you just need card tokenization and would like to handle charging/authorization yourself, version `2.1.2` has special mode called **Card Tokenization** which will grab the card details and generate the token for you.
