### ISSUE TITLE
Getting Backend issue Why?:)

### ISSUE THREAD

**Issue by Darshan-Sonigara** [Tap-Payments/goSellSDK-iOS#41]
URL response: <NSHTTPURLResponse: 0x2820dd940> { URL: https://api.tap.company/v2/init } { Status Code: 401, Headers {
    "Content-Length" =     (
        60
    );
    "Content-Type" =     (
        "application/json; charset=utf-8"
    );
    Date =     (
        "Thu, 17 Dec 2020 10:45:31 GMT"
    );
    Etag =     (
        "W/\"3c-/Wfjvfg/OrZzLhu4fMVZxJTBdrA\""
    );
    "Strict-Transport-Security" =     (
        "max-age=15552000; includeSubDomains"
    );
    "content-security-policy" =     (
        "img-src imgur.com; script-src 'self'; object-src 'none'; frame-ancestors 'none'; default-src 'none'; base-uri 'self'; form-action 'self'"
    );
    "feature-policy" =     (
        "camera 'none';autoplay 'none'"
    );
    "referrer-policy" =     (
        "no-referrer"
    );
    "x-content-security-policy" =     (
        "img-src imgur.com; script-src 'self'; object-src 'none'; frame-ancestors 'none'; default-src 'none'; base-uri 'self'; form-action 'self'"
    );
    "x-content-type-options" =     (
        nosniff
    );
    "x-dns-prefetch-control" =     (
        off
    );
    "x-download-options" =     (
        noopen
    );
    "x-frame-options" =     (
        SAMEORIGIN
    );
    "x-webkit-csp" =     (
        "img-src imgur.com; script-src 'self'; object-src 'none'; frame-ancestors 'none'; default-src 'none'; base-uri 'self'; form-action 'self'"
    );
    "x-xss-protection" =     (
        "1; mode=block"
    );
} }
TAP API SDK ERROR 
**Errors detected on the backend:**
**Error ErrorCode: Invalid API Key**

**Comment by YazanQ** [comment]
make sure you are using the right api key in 
`SecretKey(sandbox: "", production: "")`

and don't forget use sandbox key if you are in testing staging
`GoSellSDK.mode = .sandbox`

**Comment by HarshitPadalia** [comment]
I am facing same issue

**Comment by Darshan-Sonigara** [comment]
my problem is solved, I am using wrong SecretKey key
