### ISSUE TITLE
Apple Pay Using GoSell SDK

### ISSUE THREAD

**Issue by benjimkh** [Tap-Payments/goSellSDK-iOS#43]
Hello
I have managed to use apple pay ui button(which was hidden and BTW there was no method to make it visible :D )
any way after clicking it (and before that setting customer info and pay item) the bellow modal appears.untill now every thing is ok but the problem happens after tapping on **PAY WITH PASSCODE** and it shows an indicator with processing text bellow it :) 
<img width="329" alt="Screen Shot 2021-02-15 at 4 29 23 PM" src="https://user-images.githubusercontent.com/43537367/107949813-122d9500-6fab-11eb-8b51-7cda1ae6c561.png">

after the some time the processing text goes away and an alert shows which says the payment was not complete 

<img width="331" alt="Screen Shot 2021-02-15 at 4 31 55 PM" src="https://user-images.githubusercontent.com/43537367/107950050-6f294b00-6fab-11eb-8e41-112efb59cf56.png">
<img width="326" alt="Screen Shot 2021-02-15 at 4 32 32 PM" src="https://user-images.githubusercontent.com/43537367/107950060-73556880-6fab-11eb-9c7e-d425f32d590b.png">

@tapmobiledeveloper  @osamaguc  @tappayments  @halaq  @sadbar-khattak  
any help :)
oh and btw here is the request i send : 

`        let paymentItem = PKPaymentSummaryItem.init(label: "SHOE 1", amount: NSDecimalNumber(value: 100))
        let paymentNetworks = [PKPaymentNetwork.amex, .discover, .masterCard, .visa]
        if PKPaymentAuthorizationViewController.canMakePayments(usingNetworks: paymentNetworks) {
            let request = PKPaymentRequest()
            request.currencyCode = "USD" 
            request.countryCode = "US" 
            request.merchantIdentifier = "merchant.com.*********.ios" 
            request.merchantCapabilities = [.capability3DS, .capabilityEMV, .capabilityCredit] 
            request.supportedNetworks = paymentNetworks 
            request.paymentSummaryItems = [paymentItem] 
`

**Comment by halaq** [comment]
Hi @benjimkh 

Sorry for the delay reply, I just noticed your message! I will share your issue with the mobile team to contact you as soon as possible. 

BR
Hala Q.

**Comment by OsamaRabie** [comment]
@benjimkh hello, as you mentioned there is nothing to make it visible yet, it is a hidden button in the (Example) project for something under development. For now you can use apple pay supporting many countries and currencies within our checkout page in the sdk. Please refer to Apple pay section in the readme file to know the needed steps to activate Apple pay as a payment option, you will know how to generate certificates, apple merchant id, tokenize apple pay token and much more.
