### ISSUE TITLE
Getting Error in CreateChargeRequest

### ISSUE THREAD

**Issue by AbiramiBala** [Tap-Payments/goSellSDK-iOS#5]
Im getting error in creating a charge request

let request = CreateChargeRequest(amount: 1000.0, currency: "kwd", customer: self.customer, redirect: redirect)

Cannot invoke initializer for type 'CreateChargeRequest' with an argument list of type '(amount: Double, currency: String, customer: Customer, redirect: CreateChargeRedirect)'

i also tried 

CreateChargeRequest(amount: 1000.0, currency: "kwd", redirect: redirect, source: source)
(amount: 100.0, currency: "kwd", customer: self.customer, redirect: redirect, source: source)

nothing works. All these methods gives the same error.

Please help me to resolve this issue....! Thanks in advance !

**Comment by tapmobiledeveloper** [comment]
@AbiramiBala please upgrade to the SDK version 2. It has all payment process covered for UI with the flexible UI. Version 1 is no longer supported.
