### ISSUE TITLE
Always getting error in create charge method

### ISSUE THREAD

**Issue by Vishalp87** [Tap-Payments/goSellSDK-iOS#6]
Please update your library with src_all source identifier and phone key as mentioned in api doc because in create charge method it is mentioned phone as string parameter but really it should be object as per your create charge doc that content has country code & number .

Getting below error :

Serialization
Underlying error: The data couldn’t be read because it is missing.
URL response: <NSHTTPURLResponse: 0x60000041b2e0> { URL: https://api.tap.company/v2/charges/ } { Status Code: 400, Headers {
    Connection =     (
        "keep-alive"
    );
    "Content-Length" =     (
        109
    );
    "Content-Type" =     (
        "application/json"
    );
    Date =     (
        "Mon, 04 Mar 2019 05:37:49 GMT"
    );
    Etag =     (
        "W/\"6d-jkEDe8bsK4b0IpmIVyj1xMHo2nQ\""
    );
    "X-Powered-By" =     (
        Express
    );
} }

**Comment by tapmobiledeveloper** [comment]
@Vishalp87 sorry for the mess with documentation. That's because we are heavily working now on the version 2. By the way it is already released, your issue is fixed there.
