### ISSUE TITLE
Class names clashes

### ISSUE THREAD

**Issue by mats-claassen** [Tap-Payments/goSellSDK-iOS#8]
In my project I have my own classes for `Currency`, `Address`, etc. So to access the `Currency` class in `goSellSDK` I have to put the module name before it but that clashes with the name for the `goSellSDK` class.

I want to:

```swift
goSellSDK.Currency(isoCode: "USD")
```

But Xcode compiler says `Type 'goSellSDK' has no member 'Currency'` as it takes `goSellSDK` as the class and not the module.

Possible solution would be to rename either the module or the `goSellSDK` class.
Another solution, more common in ObjC than Swift, would be to prefix the classes in this library with a common prefix but this would require a name change in all classes and is not so Swifty.

**Comment by tapmobiledeveloper** [comment]
@mats-claassen thanks for the feedback.
It is [fixed](https://github.com/Tap-Payments/goSellSDK-iOS/commit/4a719e668275dd32bf868c423662a587a39c421b).

You can try it out in new version of the SDK 2.2
